name: Build and Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master   # 如果你的分支是 master，不是 main，就填 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Blazor Client Project
      run: dotnet publish ./MyBillz/FrondEnd/MyBillz/MyBillz//MyBillz.csproj -c Release -o release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./release/wwwroot
